packages:
  - apps/*
  - packages/*

allowBuilds:
  argon2: true
  cpu-features: false
  esbuild: true
  protobufjs: true
  ssh2: false

overrides:
  brace-expansion: 5.0.8
  exceljs>archiver: 8.0.0
  exceljs>unzipper: 0.12.5
  exceljs>uuid: 11.1.1
  js-yaml: 4.3.0
